"""empty message

Revision ID: 0c11143a18a2
Revises: faa3b8aa7238
Create Date: 2026-05-07 13:09:37.194370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c11143a18a2'
down_revision = 'faa3b8aa7238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidaturas', schema=None) as batch_op:
        batch_op.alter_column('id_candidatura',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=22),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_candidatura_estudante_vaga', ['id_estudante', 'id_vaga'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidaturas', schema=None) as batch_op:
        batch_op.drop_constraint('uq_candidatura_estudante_vaga', type_='unique')
        batch_op.alter_column('id_candidatura',
               existing_type=sa.String(length=22),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
