"""empty message

Revision ID: 14ce9cc0fcd0
Revises: 93381f3327b8
Create Date: 2026-04-22 09:00:19.864138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14ce9cc0fcd0'
down_revision = '93381f3327b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'ESTUDANTE', 'EMPRESA', 'FACULDADE'),
               type_=sa.Enum('MAINTAINER', 'ESTUDANTE', 'EMPRESA', 'FACULDADE', name='userrole'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('MAINTAINER', 'ESTUDANTE', 'EMPRESA', 'FACULDADE', name='userrole'),
               type_=mysql.ENUM('ADMIN', 'ESTUDANTE', 'EMPRESA', 'FACULDADE'),
               existing_nullable=False)

    # ### end Alembic commands ###
