"""Criando tabela de likes corrigida

Revision ID: 396aa03c5703
Revises: acf2728da9d3
Create Date: 2026-06-05 21:00:00.792352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396aa03c5703'
down_revision = 'acf2728da9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.String(length=36), nullable=False),
    sa.Column('id_estudante', sa.String(length=36), nullable=False),
    sa.Column('quem_curtiu', sa.String(length=20), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_estudante'], ['estudantes.id_estudante'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
