"""empty message

Revision ID: 758aa2763b42
Revises: 14ce9cc0fcd0
Create Date: 2026-04-26 18:01:14.674160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '758aa2763b42'
down_revision = '14ce9cc0fcd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vagas', schema=None) as batch_op:
        batch_op.alter_column('modalidade',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('REMOTO', 'PRESENCIAL', 'HIBRIDO', name='vagamodalidade'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('ABERTA', 'PAUSADA', 'FECHADA', 'PREENCHIDA', name='vagastatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vagas', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ABERTA', 'PAUSADA', 'FECHADA', 'PREENCHIDA', name='vagastatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('modalidade',
               existing_type=sa.Enum('REMOTO', 'PRESENCIAL', 'HIBRIDO', name='vagamodalidade'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
