"""Criando tabela de likes com id_vaga

Revision ID: 78a8f94b51ad
Revises: 396aa03c5703
Create Date: 2026-06-05 21:11:46.742967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a8f94b51ad'
down_revision = '396aa03c5703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_vaga', sa.String(length=36), nullable=False),
    sa.Column('id_estudante', sa.String(length=36), nullable=False),
    sa.Column('quem_curtiu', sa.String(length=20), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_estudante'], ['estudantes.id_estudante'], ),
    sa.ForeignKeyConstraint(['id_vaga'], ['vagas.id_vaga'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
