"""mudança dos ids para uuid quando id for privado e shortuuid quando id for publico

Revision ID: 90e23cfdf8e5
Revises: 758aa2763b42
Create Date: 2026-05-07 12:06:11.611511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90e23cfdf8e5'
down_revision = '758aa2763b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.alter_column('id_empresa',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('id_user',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('estudantes', schema=None) as batch_op:
        batch_op.alter_column('id_estudante',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('id_user',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('faculdades', schema=None) as batch_op:
        batch_op.alter_column('id_faculdade',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('id_user',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id_user',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('vagas', schema=None) as batch_op:
        batch_op.alter_column('id_vaga',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=22),
               existing_nullable=False)
        batch_op.alter_column('id_empresa',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vagas', schema=None) as batch_op:
        batch_op.alter_column('id_empresa',
               existing_type=sa.String(length=36),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)
        batch_op.alter_column('id_vaga',
               existing_type=sa.String(length=22),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id_user',
               existing_type=sa.String(length=36),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)

    with op.batch_alter_table('faculdades', schema=None) as batch_op:
        batch_op.alter_column('id_user',
               existing_type=sa.String(length=36),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)
        batch_op.alter_column('id_faculdade',
               existing_type=sa.String(length=36),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)

    with op.batch_alter_table('estudantes', schema=None) as batch_op:
        batch_op.alter_column('id_user',
               existing_type=sa.String(length=36),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)
        batch_op.alter_column('id_estudante',
               existing_type=sa.String(length=36),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.alter_column('id_user',
               existing_type=sa.String(length=36),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)
        batch_op.alter_column('id_empresa',
               existing_type=sa.String(length=36),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)

    # ### end Alembic commands ###
