"""empty message

Revision ID: 93381f3327b8
Revises: ed683cd643b3
Create Date: 2026-04-21 16:25:25.614001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93381f3327b8'
down_revision = 'ed683cd643b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.alter_column('id_user',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)

    with op.batch_alter_table('estudantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.drop_column('nome')

    with op.batch_alter_table('faculdades', schema=None) as batch_op:
        batch_op.alter_column('id_user',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculdades', schema=None) as batch_op:
        batch_op.alter_column('id_user',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)

    with op.batch_alter_table('estudantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('name')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.alter_column('id_user',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)

    # ### end Alembic commands ###
