"""adiciona campos novos ao aluno, para filtros e currículo

Revision ID: 9fbd72619fce
Revises: 78a8f94b51ad
Create Date: 2026-06-06 21:19:08.670184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fbd72619fce'
down_revision = '78a8f94b51ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('curso', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('semestre', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('disponibilidade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('area_interesse', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('curriculo_texto', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudantes', schema=None) as batch_op:
        batch_op.drop_column('curriculo_texto')
        batch_op.drop_column('area_interesse')
        batch_op.drop_column('disponibilidade')
        batch_op.drop_column('semestre')
        batch_op.drop_column('curso')

    # ### end Alembic commands ###
