"""empty message

Revision ID: a0500fcffca3
Revises: e247f4bdec25
Create Date: 2026-05-25 13:28:54.950416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0500fcffca3'
down_revision = 'e247f4bdec25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.Enum('SUCCESS', 'WARNING', 'DANGER', 'INFO', name='notificacaotipo'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
