"""empty message

Revision ID: d06123ef9606
Revises: 0c11143a18a2
Create Date: 2026-05-17 12:26:57.714039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06123ef9606'
down_revision = '0c11143a18a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacoes_verificacao',
    sa.Column('id_solicitacao', sa.String(length=22), nullable=False),
    sa.Column('ra', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('curso', sa.String(length=255), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADA', 'RECUSADA', name='solicitacaostatus'), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=False),
    sa.Column('id_user', sa.String(length=36), nullable=False),
    sa.Column('id_faculdade', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_faculdade'], ['faculdades.id_faculdade'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_solicitacao'),
    sa.UniqueConstraint('id_user', 'id_faculdade', name='uq_solicitacao_user_faculdade')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacoes_verificacao')
    # ### end Alembic commands ###
