"""add estudante, empresa, faculdade

Revision ID: ed683cd643b3
Revises: 5e92698b54ef
Create Date: 2026-03-29 17:42:12.464038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed683cd643b3'
down_revision = '5e92698b54ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id_empresa', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('ramo', sa.String(length=255), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('id_user', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_empresa'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('id_user')
    )
    op.create_table('estudantes',
    sa.Column('id_estudante', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('id_user', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_estudante'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('id_user')
    )
    op.create_table('faculdades',
    sa.Column('id_faculdade', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('id_user', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_faculdade'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('id_user')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDENTE', 'VERIFICADO', 'REJEITADO', name='userstatus'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('faculdades')
    op.drop_table('estudantes')
    op.drop_table('empresas')
    # ### end Alembic commands ###
