"""adição da tabela de candidatura

Revision ID: faa3b8aa7238
Revises: 90e23cfdf8e5
Create Date: 2026-05-07 12:34:10.990298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa3b8aa7238'
down_revision = '90e23cfdf8e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidaturas',
    sa.Column('id_candidatura', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADO', 'RECUSADO', name='candidaturastatus'), nullable=False),
    sa.Column('data_candidatura', sa.DateTime(), nullable=False),
    sa.Column('id_estudante', sa.String(length=36), nullable=False),
    sa.Column('id_vaga', sa.String(length=22), nullable=False),
    sa.ForeignKeyConstraint(['id_estudante'], ['estudantes.id_estudante'], ),
    sa.ForeignKeyConstraint(['id_vaga'], ['vagas.id_vaga'], ),
    sa.PrimaryKeyConstraint('id_candidatura')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidaturas')
    # ### end Alembic commands ###
